StoreTanPhat/Models/PhanHoiBinhLuan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class PhanHoiBinhLuan
    {

        [Display(Name = "Phản Hồi Bình Luận")]
        public int ID_PhanHoiBinhLuan { get; set; }

        [Display(Name = "Bình Luận")]
        public int ID_BinhLuan { get; set; }

        [Display(Name = "Nội Dung")]
        public string NoiDung { get; set; }

        [Display(Name = "Khách Hàng")]
        public Nullable<int> ID_KhachHang { get; set; }

        [Display(Name = "Nhân Viên")]
        public Nullable<int> ID_NhanVien { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name = "Ngày Bình Luận")]
        public System.DateTime NgayBinhLuan { get; set; }

        [Display(Name = "Hiển Thị")]
        public int HienThi { get; set; }

        public HttpPostedFileBase DuLieuHinhAnh { get; set; }

        [Display(Name = "Bình Luận")]
        public virtual BinhLuan BinhLuan { get; set; }

        [Display(Name = "Khách Hàng")]
        public virtual KhachHang KhachHang { get; set; }

        [Display(Name = "Nhân Viên")]
        public virtual NhanVien NhanVien { get; set; }
    }
}

StoreTanPhat/Areas/Admin/Controllers/PhanHoiBinhLuanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreTanPhat.Areas.Admin.Controllers;
using StoreTanPhat.Models;

namespace StoreTanPhat.Areas.Admin.Controllers
{
    public class PhanHoiBinhLuanController : AuthController
    {
        private ShopTanPhatEntities db = new ShopTanPhatEntities();

        // GET: Admin/PhanHoiBinhLuan
        public ActionResult Index(int ?id)
        {
            if(id == null)
            {
                return RedirectToAction("Index", "BinhLuan");
            }
            var phanHoiBinhLuan = db.PhanHoiBinhLuan.Include(p => p.BinhLuan).Include(p => p.KhachHang).Include(p => p.NhanVien);
            Session["ID_BinhLuan"] = id;
            return View(phanHoiBinhLuan.Where(m=>m.ID_BinhLuan == id).ToList());
        }

        // GET: Admin/PhanHoiBinhLuan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanHoiBinhLuan phanHoiBinhLuan = db.PhanHoiBinhLuan.Find(id);
            if (phanHoiBinhLuan == null)
            {
                return HttpNotFound();
            }
            return View(phanHoiBinhLuan);
        }

        // GET: Admin/PhanHoiBinhLuan/Create
        public ActionResult Create()
        {
            ViewBag.ID_BinhLuan = new SelectList(db.BinhLuan, "ID_BinhLuan", "NoiDung");
            ViewBag.ID_KhachHang = new SelectList(db.KhachHang, "ID_KhachHang", "HoTen");
            ViewBag.ID_NhanVien = new SelectList(db.NhanVien, "ID_NhanVien", "TenNhanVien");
            return View();
        }

        // POST: Admin/PhanHoiBinhLuan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PhanHoiBinhLuan,ID_BinhLuan,NoiDung,ID_KhachHang,ID_NhanVien,HinhAnh,DuLieuHinhAnh,NgayBinhLuan,HienThi")] PhanHoiBinhLuan phanHoiBinhLuan)
        {
            if (ModelState.IsValid)
            {
                var result = UploadImage(phanHoiBinhLuan.DuLieuHinhAnh);
                if (phanHoiBinhLuan.DuLieuHinhAnh == null)
                {
                    phanHoiBinhLuan.HinhAnh = "/Images/Comment/No_Image.png";
                }
                else
                {
                    if (result == "ErrorType")
                    {
                        ViewBag.Error = "Vui lòng chọn đúng kiểu";
                        return View(phanHoiBinhLuan);
                    }
                    if (result == "ErrorSize")
                    {
                        ViewBag.Error = "Vui lòng chọn đúng kích thước";
                        return View(phanHoiBinhLuan);
                    }
                    else
                    {
                        phanHoiBinhLuan.HinhAnh = result;
                    }
                }
                phanHoiBinhLuan.ID_BinhLuan = (int)Session["ID_BinhLuan"];
                phanHoiBinhLuan.NgayBinhLuan = DateTime.Now;
                phanHoiBinhLuan.ID_NhanVien = 1;
                phanHoiBinhLuan.HienThi = 1;
                db.PhanHoiBinhLuan.Add(phanHoiBinhLuan);
                db.SaveChanges();
                return RedirectToAction("Index",new{ id = (int)Session["ID_BinhLuan"] });
            }

            ViewBag.ID_BinhLuan = new SelectList(db.BinhLuan, "ID_BinhLuan", "NoiDung", phanHoiBinhLuan.ID_BinhLuan);
            ViewBag.ID_KhachHang = new SelectList(db.KhachHang, "ID_KhachHang", "HoTen", phanHoiBinhLuan.ID_KhachHang);
            ViewBag.ID_NhanVien = new SelectList(db.NhanVien, "ID_NhanVien", "TenNhanVien", phanHoiBinhLuan.ID_NhanVien);
            return View(phanHoiBinhLuan);
        }

        // GET: Admin/PhanHoiBinhLuan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanHoiBinhLuan phanHoiBinhLuan = db.PhanHoiBinhLuan.Find(id);
            if (phanHoiBinhLuan == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_BinhLuan = new SelectList(db.BinhLuan, "ID_BinhLuan", "NoiDung", phanHoiBinhLuan.ID_BinhLuan);
            ViewBag.ID_KhachHang = new SelectList(db.KhachHang, "ID_KhachHang", "HoTen", phanHoiBinhLuan.ID_KhachHang);
            ViewBag.ID_NhanVien = new SelectList(db.NhanVien, "ID_NhanVien", "TenNhanVien", phanHoiBinhLuan.ID_NhanVien);
            return View(phanHoiBinhLuan);
        }

        // POST: Admin/PhanHoiBinhLuan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_PhanHoiBinhLuan,ID_BinhLuan,NoiDung,ID_KhachHang,ID_NhanVien,HinhAnh,NgayBinhLuan,HienThi")] PhanHoiBinhLuan phanHoiBinhLuan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phanHoiBinhLuan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_BinhLuan = new SelectList(db.BinhLuan, "ID_BinhLuan", "NoiDung", phanHoiBinhLuan.ID_BinhLuan);
            ViewBag.ID_KhachHang = new SelectList(db.KhachHang, "ID_KhachHang", "HoTen", phanHoiBinhLuan.ID_KhachHang);
            ViewBag.ID_NhanVien = new SelectList(db.NhanVien, "ID_NhanVien", "TenNhanVien", phanHoiBinhLuan.ID_NhanVien);
            return View(phanHoiBinhLuan);
        }

        // GET: Admin/PhanHoiBinhLuan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanHoiBinhLuan phanHoiBinhLuan = db.PhanHoiBinhLuan.Find(id);
            if (phanHoiBinhLuan == null)
            {
                return HttpNotFound();
            }
            return View(phanHoiBinhLuan);
        }

        // POST: Admin/PhanHoiBinhLuan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhanHoiBinhLuan phanHoiBinhLuan = db.PhanHoiBinhLuan.Find(id);
            DeleteImage(phanHoiBinhLuan.HinhAnh);
            db.PhanHoiBinhLuan.Remove(phanHoiBinhLuan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public string UploadImage(HttpPostedFileBase file)
        {
            string folder = "Images/Comment/";
            string fileName = "";
            if (file != null)
            {
                string fileExtension = Path.GetExtension(file.FileName).ToLower();
                var fileTypeSupported = new[] { ".jpg", ".jpeg", ".png", ".gif" };
                if (!fileTypeSupported.Contains(fileExtension))
                {
                    return "ErrorType";
                }
                if (file.ContentLength > 2 * 1024 * 1024)
                {
                    return "ErrorSize";
                }
                else
                {
                    fileName = Guid.NewGuid().ToString() + fileExtension;
                    string filePath = Path.Combine(Server.MapPath("~/" + folder), fileName);
                    file.SaveAs(filePath);
                }
            }
            return folder + fileName;
        }

        public void DeleteImage(string path)
        {
            string oldFilePath = Server.MapPath("~/" + path);
            if (System.IO.File.Exists(oldFilePath)) System.IO.File.Delete(oldFilePath);
        }
    }
}

StoreTanPhat/Areas/Admin/Views/PhanHoiBinhLuan/Create.cshtml
@model StoreTanPhat.Models.PhanHoiBinhLuan

@{
    ViewBag.Title = "THÊM MỚI PHẢN HỒI";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm("Create", "PhanHoiBinhLuan", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DuLieuHinhAnh)
                <br />
                @Html.TextBoxFor(model => model.DuLieuHinhAnh, new { @class = "form-control-file", type = "file" })
                @Html.ValidationMessageFor(model => model.DuLieuHinhAnh, "", new { @class = "text-danger" })
                <br />
                @if (ViewBag.Error != null)
                {
                    <p class="badge rounded-pill badge-danger text-white" style="font-size:15px;font-weight:bold">@ViewBag.Error</p>
                }
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm Mới" class="btn btn-default" /> hoặc <span class="btn btn-info">@Html.ActionLink("Trở về trang chính", "Index")</span>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreTanPhat/Areas/Admin/Views/PhanHoiBinhLuan/Delete.cshtml
@model StoreTanPhat.Models.PhanHoiBinhLuan

@{
    ViewBag.Title = "XÓA PHẢN HỒI";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card mt-3 border border-primary">
    <h5 class="card-header bg-primary text-white">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm("Delete", "ThuongHieu"))
        {
            @Html.AntiForgeryToken()

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                Bạn có muốn xóa phản hồi của <strong>@Model.KhachHang.HoTen</strong> không?
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="form-actions no-color">
                <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> hoặc <a class="btn btn-warning" href="@Url.Action("Index")">Trở về trang chủ</a>
            </div>
        }
    </div>
</div>

StoreTanPhat/Areas/Admin/Views/PhanHoiBinhLuan/Edit.cshtml
@model StoreTanPhat.Models.PhanHoiBinhLuan

@{
    ViewBag.Title = "SỬA BÌNH LUẬN";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm("Edit", "PhanHoiBinhLuan", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID_PhanHoiBinhLuan)

            <div class="form-group">
                @Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DuLieuHinhAnh)
                <br />
                @Html.TextBoxFor(model => model.DuLieuHinhAnh, new { @class = "form-control-file", type = "file" })
                @Html.ValidationMessageFor(model => model.DuLieuHinhAnh, "", new { @class = "text-danger" })
                <br />
                <input type="hidden" value="@Model.HinhAnh" name="OldImage" />
                @if (ViewBag.Error != null)
                {
                    <p class="badge rounded-pill badge-danger text-white" style="font-size:15px;font-weight:bold">@ViewBag.Error</p>
                }
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Cập Nhật" class="btn btn-default" /> hoặc <span class="btn btn-info">@Html.ActionLink("Trở về trang chính", "Index")</span>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreTanPhat/Areas/Admin/Views/PhanHoiBinhLuan/Index.cshtml
@model IEnumerable<StoreTanPhat.Models.PhanHoiBinhLuan>

@{
    ViewBag.Title = "QUẢN LÝ PHẢN HỒI";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    a {
        color: white;
    }

    a:hover {
        color: white;
    }
</style>

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        <p class="btn btn-primary">
            @Html.ActionLink("Thêm mới", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NoiDung)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HinhAnh)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayBinhLuan)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HienThi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BinhLuan.NoiDung)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.KhachHang.HoTen)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NhanVien.TenNhanVien)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NoiDung)
                    </td>
                    <td>
                        @if (item.HinhAnh == "/Images/Comment/No_Image.png")
                        {
                            <img src="~/Images/Comment/No_Image.png" width="100" />
                        }
                        else
                        {
                            <img src="~/@item.HinhAnh" width="100" />
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayBinhLuan)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HienThi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BinhLuan.NoiDung)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KhachHang.HoTen)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NhanVien.TenNhanVien)
                    </td>
                    <td>
                        <a class="btn btn-info text-white" href="@Url.Action("Edit", "PhanHoiBinhLuan", new { id = item.ID_PhanHoiBinhLuan })">Sửa</a> <span> |</span>
                        <a class="btn btn-danger text-white" href="@Url.Action("Delete", "PhanHoiBinhLuan", new { id = item.ID_PhanHoiBinhLuan })">Xóa</a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>