StoreTanPhat/Models/SanPhamLienQuan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPhamLienQuan
    {
        [Display(Name = "Sản Phẩm Liên Quan")]
        public int ID_SPLQ { get; set; }

        [Display(Name = "Slider")]
        public int ID_Slider { get; set; }

        [Display(Name = "Sản Phẩm")]
        [Required(ErrorMessage = "Vui lòng chọn sản phẩm")]
        public int ID_SanPham { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual Slider Slider { get; set; }
    }
}

StoreTanPhat/Areas/Admin/Controllers/SanPhamLienQuanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreTanPhat.Areas.Admin.Controllers;
using StoreTanPhat.Models;

namespace StoreTanPhat.Areas.Admin.Controllers
{
    public class SanPhamLienQuanController : AuthController
    {
        private ShopTanPhatEntities db = new ShopTanPhatEntities();

        // GET: Admin/SanPhamLienQuan
        public ActionResult Index(int ?id)
        {
            if(id == null)
            {
                return RedirectToAction("Index", "Slider"); 
            }
            var sanPhamLienQuan = db.SanPhamLienQuan.Include(s => s.SanPham).Include(s => s.Slider).Where(m=>m.ID_Slider == id);
            Session["ID_Slider"] = id;
            return View(sanPhamLienQuan.ToList());
        }

        // GET: Admin/SanPhamLienQuan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPhamLienQuan sanPhamLienQuan = db.SanPhamLienQuan.Find(id);
            if (sanPhamLienQuan == null)
            {
                return HttpNotFound();
            }
            return View(sanPhamLienQuan);
        }

        // GET: Admin/SanPhamLienQuan/Create
        public ActionResult Create()
        {
            if(Session["ID_Slider"] == null)
            {
                return RedirectToAction("Index", "Slider");
            }
            ViewBag.ID_SanPham = new SelectList(db.SanPham, "ID_SanPham", "TenSanPham");
            ViewBag.ID_Slider = new SelectList(db.Slider, "Id_Slider", "TenSilder");
            return View();
        }

        // POST: Admin/SanPhamLienQuan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_SPLQ,ID_Slider,ID_SanPham")] SanPhamLienQuan sanPhamLienQuan)
        {
            ViewBag.ID_SanPham = new SelectList(db.SanPham, "ID_SanPham", "TenSanPham", sanPhamLienQuan.ID_SanPham);
            ViewBag.ID_Slider = new SelectList(db.Slider, "Id_Slider", "TenSilder", sanPhamLienQuan.ID_Slider);
            if (ModelState.IsValid)
            {
                int ID_Silder = (int)Session["ID_Slider"];
                foreach(var item in db.SanPhamLienQuan.Where(m=>m.ID_Slider == ID_Silder).ToList())
                {
                    if(item.ID_SanPham == sanPhamLienQuan.ID_SanPham)
                    {
                        ViewBag.Error = "Sản phẩm này đã tồn tại";
                        return View(sanPhamLienQuan);
                    }
                }

                if(sanPhamLienQuan.SanPham.TinhTrangHienThi == 0)
                {
                    return RedirectToAction("Index");
                }
                sanPhamLienQuan.ID_Slider = (int)Session["ID_Slider"];
                db.SanPhamLienQuan.Add(sanPhamLienQuan);
                db.SaveChanges();
                return RedirectToAction("Index",new { id = Session["ID_Slider"] });
            }
            return View(sanPhamLienQuan);
        }

        // GET: Admin/SanPhamLienQuan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPhamLienQuan sanPhamLienQuan = db.SanPhamLienQuan.Find(id);
            if (sanPhamLienQuan == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_SanPham = new SelectList(db.SanPham, "ID_SanPham", "TenSanPham", sanPhamLienQuan.ID_SanPham);
            ViewBag.ID_Slider = new SelectList(db.Slider, "Id_Slider", "TenSilder", sanPhamLienQuan.ID_Slider);
            return View(sanPhamLienQuan);
        }

        // POST: Admin/SanPhamLienQuan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_SPLQ,ID_Slider,ID_SanPham")] SanPhamLienQuan sanPhamLienQuan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPhamLienQuan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_SanPham = new SelectList(db.SanPham, "ID_SanPham", "TenSanPham", sanPhamLienQuan.ID_SanPham);
            ViewBag.ID_Slider = new SelectList(db.Slider, "Id_Slider", "TenSilder", sanPhamLienQuan.ID_Slider);
            return View(sanPhamLienQuan);
        }

        // GET: Admin/SanPhamLienQuan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["ID_Slider"] == null)
            {
                return RedirectToAction("Index", "Slider");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                SanPhamLienQuan sanPhamLienQuan = db.SanPhamLienQuan.Find(id);
                if (sanPhamLienQuan == null)
                {
                    return HttpNotFound();
                }
                return View(sanPhamLienQuan);
            }
        }

        // POST: Admin/SanPhamLienQuan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPhamLienQuan sanPhamLienQuan = db.SanPhamLienQuan.Find(id);
            db.SanPhamLienQuan.Remove(sanPhamLienQuan);
            db.SaveChanges();
            Session.Remove("ID_Slider");
            return RedirectToAction("Index", new { id = Session["ID_Slider"] });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreTanPhat/Areas/Admin/Views/SanPhamLienQuan/Create.cshtml
@model StoreTanPhat.Models.SanPhamLienQuan

@{
    ViewBag.Title = "THÊM SẢN PHẨM";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    a{
        color:white;
    }
    a:hover{
        color:white;
    }
</style>

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @if (ViewBag.Error != null)
        {
            <span class="badge bg-danger text-white">@ViewBag.Error</span>
        }

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>SanPhamLienQuan</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.ID_SanPham, "ID_SanPham", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.DropDownList("ID_SanPham", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ID_SanPham, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-primary text-white" /> hoặc <span class="btn btn-info">@Html.ActionLink("Back to List", "Index")</span>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

StoreTanPhat/Areas/Admin/Views/SanPhamLienQuan/Delete.cshtml
@model StoreTanPhat.Models.SanPhamLienQuan

@{
    ViewBag.Title = "XÓA SẢN PHẨM";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h5 class="card-header bg-primary text-white">@ViewBag.Title</h5>
<div class="card-body">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            Bạn có muốn xóa sản phẩm <strong>@Model.SanPham.TenSanPham</strong> không?
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> hoặc <a class="btn btn-warning" href="@Url.Action("Index")">Trở về trang chủ</a>
        </div>
    }
</div>
</div>

StoreTanPhat/Areas/Admin/Views/SanPhamLienQuan/Index.cshtml
@model IEnumerable<StoreTanPhat.Models.SanPhamLienQuan>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        <p class="btn btn-primary">
            @Html.ActionLink("Thêm Mới", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.SanPham.TenSanPham)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Slider.TenSilder)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.SanPham.TenSanPham)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Slider.TenSilder)
                    </td>
                    <td>
                        <a class="btn btn-danger text-white" href="@Url.Action("Delete", "SanPhamLienQuan", new { id = item.ID_SPLQ })">Xóa</a>

                    </td>
                </tr>
            }

        </table>

    </div>
</div>