StoreTanPhat/Models/MaGiamGia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MaGiamGia
    {

        [Display(Name = "Mã Giảm Giá")]
        public int Id_MaGiamGia { get; set; }

        [Display(Name = "Code")]
        [Required(ErrorMessage ="Vui lòng nhập Code")]
        public string KeyGiamGia { get; set; }

        [Display(Name = "Giá Tiền Gỉảm")]
        [Required(ErrorMessage ="Vui lòng nhập giá tiền giảm")]
        public int TienGiam { get; set; }

        [Display(Name = "Ngày Bắt Đầu")]
        [Required(ErrorMessage = "Vui lòng chọn ngày bắt đầu")]
        [DataType(DataType.Date)]
        public System.DateTime NgayBatDau { get; set; }

        [Display(Name = "Ngày Hết Hạn")]
        [Required(ErrorMessage = "Vui lòng chọn ngày kết thúc")]
        [DataType(DataType.Date)]
        public System.DateTime NgayKetThuc { get; set; }

        [Display(Name = "Tình Trạng")]
        [Required(ErrorMessage = "Vui lòng chọn tình trạng")]
        public int TinhTrangHienThi { get; set; }
    }
}

StoreTanPhat/Areas/Admin/Controllers/MaGiamGiaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreTanPhat.Areas.Admin.Controllers;
using StoreTanPhat.Models;

namespace StoreTanPhat.Areas.Admin.Controllers
{
    public class MaGiamGiaController : AuthController
    {
        private ShopTanPhatEntities db = new ShopTanPhatEntities();

        // GET: Admin/MaGiamGia
        public ActionResult Index()
        {
            return View(db.MaGiamGia.ToList());
        }

        // GET: Admin/MaGiamGia/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaGiamGia maGiamGia = db.MaGiamGia.Find(id);
            if (maGiamGia == null)
            {
                return HttpNotFound();
            }
            return View(maGiamGia);
        }

        // GET: Admin/MaGiamGia/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/MaGiamGia/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_MaGiamGia,KeyGiamGia,TienGiam,NgayBatDau,NgayKetThuc,TinhTrangHienThi")] MaGiamGia maGiamGia)
        {
            if (ModelState.IsValid)
            {
                db.MaGiamGia.Add(maGiamGia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(maGiamGia);
        }

        // GET: Admin/MaGiamGia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaGiamGia maGiamGia = db.MaGiamGia.Find(id);
            if (maGiamGia == null)
            {
                return HttpNotFound();
            }
            return View(maGiamGia);
        }

        // POST: Admin/MaGiamGia/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_MaGiamGia,KeyGiamGia,TienGiam,NgayBatDau,NgayKetThuc,TinhTrangHienThi")] MaGiamGia maGiamGia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(maGiamGia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(maGiamGia);
        }

        // GET: Admin/MaGiamGia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaGiamGia maGiamGia = db.MaGiamGia.Find(id);
            if (maGiamGia == null)
            {
                return HttpNotFound();
            }
            return View(maGiamGia);
        }

        // POST: Admin/MaGiamGia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MaGiamGia maGiamGia = db.MaGiamGia.Find(id);
            db.MaGiamGia.Remove(maGiamGia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreTanPhat/Areas/Admin/Views/MaGiamGia/Create.cshtml
@model StoreTanPhat.Models.MaGiamGia

@{
    ViewBag.Title = "Thêm Mới";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>MaGiamGia</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.KeyGiamGia, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.KeyGiamGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KeyGiamGia, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TienGiam, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.TienGiam, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TienGiam, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgayBatDau, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgayKetThuc, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TinhTrangHienThi)
                    @Html.DropDownListFor(model => model.TinhTrangHienThi, new SelectList(new[] {
                        new SelectListItem {Value = null, Text = "-- Chọn --" },
                        new SelectListItem {Value = "0", Text = "Ẩn đi" },
                        new SelectListItem {Value = "1", Text = "Hiện ra" },
                    }, "Value", "Text"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TinhTrangHienThi, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Thêm Mới" class="btn btn-default" /> hoặc <span class="btn btn-info">@Html.ActionLink("Trở về danh sách", "Index")</span>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

StoreTanPhat/Areas/Admin/Views/MaGiamGia/Delete.cshtml
@model StoreTanPhat.Models.MaGiamGia

@{
    ViewBag.Title = "XÓA GIẢM GIÁ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card mt-3 border border-primary">
    <h5 class="card-header bg-primary text-white">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                Bạn có muốn xóa mã giảm giá <strong>@Model.KeyGiamGia</strong> không?
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="form-actions no-color">
                <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> hoặc <a class="btn btn-warning" href="@Url.Action("Index")">Trở về trang chủ</a>
            </div>
        }
    </div>
</div>

StoreTanPhat/Areas/Admin/Views/MaGiamGia/Edit.cshtml
@model StoreTanPhat.Models.MaGiamGia

@{
    ViewBag.Title = "SỬA MÃ GIẢM GIÁ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id_MaGiamGia)

                <div class="form-group">
                    @Html.LabelFor(model => model.KeyGiamGia, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.KeyGiamGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KeyGiamGia, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TienGiam, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.TienGiam, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TienGiam, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgayBatDau, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgayKetThuc, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TinhTrangHienThi)
                    @Html.DropDownListFor(model => model.TinhTrangHienThi, new SelectList(new[] {
                        new SelectListItem {Value = null, Text = "-- Chọn --" },
                        new SelectListItem {Value = "0", Text = "Ẩn đi" },
                        new SelectListItem {Value = "1", Text = "Hiện ra" },
                    }, "Value", "Text"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TinhTrangHienThi, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Cập Nhật" class="btn btn-default" /> hoặc <span class="btn btn-info">@Html.ActionLink("Trở về danh sách", "Index")</span>
                    </div>
                </div>
        }
    </div>
</div>

StoreTanPhat/Areas/Admin/Views/MaGiamGia/Index.cshtml
@model IEnumerable<StoreTanPhat.Models.MaGiamGia>

@{
    ViewBag.Title = "QUẢN LÝ MÃ GIẢM GIÁ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<style>
    a{
        color:white;
    }
    a:hover{
        color:white;
    }
</style>

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        <p class="btn btn-primary">
            @Html.ActionLink("Thêm Mới", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.KeyGiamGia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TienGiam)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayBatDau)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayKetThuc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TinhTrangHienThi)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.KeyGiamGia)
                    </td>
                    <td>
                        @item.TienGiam.ToString("N0")đ
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayBatDau)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayKetThuc)
                    </td>
                    <td>
                        @if (item.TinhTrangHienThi == 1)
                        {
                            <span class="badge bg-success">Hiển thị</span>
                        }
                        else
                        {
                            <span class="badge bg-danger">Ẩn đi</span>
                        }
                    </td>
                    <td>
                        <a class="btn btn-danger text-white" href="@Url.Action("Delete", "MaGiamGia", new { id = item.Id_MaGiamGia })">Xóa</a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>