StoreTanPhat/Models/DatHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreTanPhat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatHang()
        {
            this.DatHangChiTiet = new HashSet<DatHangChiTiet>();
        }

        [Display(Name = "Đặt Hàng")]
        public int ID_DatHang { get; set; }

        [Display(Name = "Khách Hàng")]
        public int ID_KhachHang { get; set; }

        [Display(Name = "Phí Ship")]
        public Nullable<int> PhiShip { get; set; }

        [Display(Name = "Địa Chỉ Giao Hàng")]
        public string DiaChiGiaoHang { get; set; }

        [Display(Name = "Họ Tên")]
        public string HoTenNguoiNhan { get; set; }

        [Display(Name = "Phone")]
        public string SoDienThoai { get; set; }

        [Display(Name = "Ngày Lập Đơn")]
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }

        [Display(Name = "Tổng Tiền")]
        public int TongTien { get; set; }

        [Display(Name = "Tình Trạng")]
        public int TinhTrangDonHang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangChiTiet> DatHangChiTiet { get; set; }
    }
}

StoreTanPhat/Areas/Admin/Controllers/DatHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreTanPhat.Areas.Admin.Controllers;
using StoreTanPhat.Models;

namespace StoreTanPhat.Areas.Admin.Controllers
{
    public class DatHangController : AuthController
    {
        private ShopTanPhatEntities db = new ShopTanPhatEntities();

        // GET: Admin/DatHang
        public ActionResult Index()
        {
            var datHang = db.DatHang.Include(d => d.KhachHang);
            return View(datHang.ToList());
        }

        // GET: Admin/DatHang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatHang datHang = db.DatHang.Find(id);
            if (datHang == null)
            {
                return HttpNotFound();
            }
            return View(datHang);
        }

        // GET: Admin/DatHang/Create
        public ActionResult Create()
        {
            ViewBag.ID_KhachHang = new SelectList(db.KhachHang, "ID_KhachHang", "HoTen");
            return View();
        }

        // POST: Admin/DatHang/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_DatHang,ID_KhachHang,PhiShip,DiaChiGiaoHang,HoTenNguoiNhan,SoDienThoai,NgayLap,NgayCapNhat,TongTien,TinhTrangDonHang")] DatHang datHang)
        {
            var list = db.DatHangChiTiet.Where(m => m.ID_DatHang == datHang.ID_DatHang).ToList();
            if (ModelState.IsValid)
            {
                db.DatHang.Add(datHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_KhachHang = new SelectList(db.KhachHang, "ID_KhachHang", "HoTen", datHang.ID_KhachHang);
            return View(datHang);
        }

        // GET: Admin/DatHang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatHang datHang = db.DatHang.Find(id);
            if (datHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_KhachHang = new SelectList(db.KhachHang, "ID_KhachHang", "HoTen", datHang.ID_KhachHang);
            return View(datHang);
        }

        // POST: Admin/DatHang/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_DatHang,ID_KhachHang,PhiShip,DiaChiGiaoHang,HoTenNguoiNhan,SoDienThoai,NgayLap,NgayCapNhat,TongTien,TinhTrangDonHang")] DatHang datHang)
        {
            if (ModelState.IsValid)
            {
                datHang.NgayCapNhat = DateTime.Now;
                db.Entry(datHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_KhachHang = new SelectList(db.KhachHang, "ID_KhachHang", "HoTen", datHang.ID_KhachHang);
            return View(datHang);
        }

        // GET: Admin/DatHang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DatHang datHang = db.DatHang.Find(id);
            if (datHang == null)
            {
                return HttpNotFound();
            }
            return View(datHang);
        }

        // POST: Admin/DatHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DatHang datHang = db.DatHang.Find(id);
            db.DatHang.Remove(datHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreTanPhat/Areas/Admin/Views/DatHang/Delete.cshtml
@model StoreTanPhat.Models.DatHang

@{
    ViewBag.Title = "XOÁ ĐẶT HÀNG";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card mt-3 border border-primary">
    <h5 class="card-header bg-primary text-white">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                Bạn có muốn xóa đặt hàng của <strong>@Model.KhachHang.HoTen</strong> không?
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="form-actions no-color">
                <input type="submit" value="Xác nhận xóa" class="btn btn-danger" /> hoặc <a class="btn btn-warning" href="@Url.Action("Index")">Trở về trang chủ</a>
            </div>
        }
    </div>
</div>

StoreTanPhat/Areas/Admin/Views/DatHang/Edit.cshtml
@model StoreTanPhat.Models.DatHang

@{
    ViewBag.Title = "SỬA ĐẶT HÀNG";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID_DatHang)

            @Html.HiddenFor(m => m.ID_KhachHang)

            @Html.HiddenFor(m => m.PhiShip)

            <div class="form-group">
                @Html.LabelFor(model => model.DiaChiGiaoHang, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.DiaChiGiaoHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChiGiaoHang, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HoTenNguoiNhan, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.HoTenNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTenNguoiNhan, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SoDienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
            </div>

            @Html.HiddenFor(m => m.NgayLap)
            @Html.HiddenFor(m => m.TongTien)

            <div class="form-group">
                @Html.LabelFor(model => model.TinhTrangDonHang)
                @Html.DropDownListFor(model => model.TinhTrangDonHang, new SelectList(new[] {
                    new SelectListItem {Value = null, Text = "-- Chọn --" },
                     new SelectListItem {Value = "2", Text = "Đã hủy" },
                    new SelectListItem {Value = "3", Text = "Đang đóng gói" },
                     new SelectListItem {Value = "4", Text = "Đang gửi vận chuyển" },
                    new SelectListItem {Value = "5", Text = "Đang chuyển" },
                     new SelectListItem {Value = "6", Text = "Thất bại" },
                    new SelectListItem {Value = "7", Text = "Đang chuyển hoàn" },
                     new SelectListItem {Value = "8", Text = "Đã chuyển hoàn" },
                    new SelectListItem {Value = "9", Text = "Chờ Xác Thực" },
                    new SelectListItem {Value = "10", Text = "Thành công" },
                }, "Value", "Text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TinhTrangDonHang, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="CẬP NHẬT" class="btn btn-outline-primary" /> hoặc <span class="btn btn-info">@Html.ActionLink("Trở về danh sách", "Index")</span>
                </div>
            </div>
        }
    </div>
</div>

StoreTanPhat/Areas/Admin/Views/DatHang/Index.cshtml
@model IEnumerable<StoreTanPhat.Models.DatHang>

@{
    ViewBag.Title = "QUẢN LÝ ĐẶT HÀNG";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="card border-primary">
    <h5 class="card-header bg-primary text-white">@ViewBag.Title</h5>
    <div class="card-body">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PhiShip)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DiaChiGiaoHang)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HoTenNguoiNhan)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SoDienThoai)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgayLap)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TongTien)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TinhTrangDonHang)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhiShip)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DiaChiGiaoHang)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTenNguoiNhan)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoDienThoai)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgayLap)
                    </td>
                    <td>
                        @item.TongTien.ToString("N0")<span>đ</span>
                    </td>
                    <td>
                        @if (item.TinhTrangDonHang == 0)
                        {
                            <span>Đơn hàng mới</span>
                        }
                        else if (item.TinhTrangDonHang == 1)
                        {
                            <span>Đã xác nhận</span>
                        }
                        else if (item.TinhTrangDonHang == 2)
                        {
                            <span>Đã hủy</span>
                        }
                        else if (item.TinhTrangDonHang == 3)
                        {
                            <span>Đang đóng gói</span>
                        }
                        else if (item.TinhTrangDonHang == 4)
                        {
                            <span>Đang gởi vận chuyển</span>
                        }
                        else if (item.TinhTrangDonHang == 5)
                        {
                            <span>Đang chuyển</span>
                        }
                        else if (item.TinhTrangDonHang == 6)
                        {
                            <span>Thất bại</span>
                        }
                        else if (item.TinhTrangDonHang == 7)
                        {
                            <span>Đang chuyển hoàn</span>
                        }
                        else if (item.TinhTrangDonHang == 8)
                        {
                            <span>Đã chuyển hoàn</span>
                        }
                        else if (item.TinhTrangDonHang == 9)
                        {
                            <span>Chờ xác thực</span>
                        }
                        else
                        {
                            <span>Thành công</span>
                        }
                    </td>
                    <td>
                        @if (item.TinhTrangDonHang != 2)
                        {
                            <a class="btn btn-primary" href="@Url.Action("Index","DatHangChiTiet", new { id = item.ID_DatHang })">Chi Tiết</a>
                        }
                    </td>

                    <td>
                        @if (item.TinhTrangDonHang != 2 || item.TinhTrangDonHang == 9)
                        {
                            <a class="btn btn-info" href="@Url.Action("Edit", "DatHang", new { id = item.ID_DatHang })">Sửa</a>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>